# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T12:34:44+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel, SecretStr, conint, constr


class AccessDeniedException(RootModel[Any]):
    root: Any


class AccessorBillingTokenString(RootModel[constr(min_length=42, max_length=42)]):
    root: constr(min_length=42, max_length=42)


class AccessorListMaxResults(RootModel[conint(ge=1, le=50)]):
    root: conint(ge=1, le=50)


class AccessorStatus(Enum):
    AVAILABLE = 'AVAILABLE'
    PENDING_DELETION = 'PENDING_DELETION'
    DELETED = 'DELETED'


class AccessorType(Enum):
    BILLING_TOKEN = 'BILLING_TOKEN'


class ArnString(
    RootModel[constr(pattern=r'^arn:.+:.+:.+:.+:.+', min_length=1, max_length=1011)]
):
    root: constr(pattern=r'^arn:.+:.+:.+:.+:.+', min_length=1, max_length=1011)


class AvailabilityZoneString(RootModel[str]):
    root: str


class ClientRequestTokenString(RootModel[constr(min_length=1, max_length=64)]):
    root: constr(min_length=1, max_length=64)


class DeleteAccessorInput(BaseModel):
    pass


class DeleteAccessorOutput(BaseModel):
    pass


class DeleteMemberInput(BaseModel):
    pass


class DeleteMemberOutput(BaseModel):
    pass


class DeleteNodeInput(BaseModel):
    pass


class DeleteNodeOutput(BaseModel):
    pass


class DescriptionString(RootModel[constr(max_length=128)]):
    root: constr(max_length=128)


class Edition(Enum):
    STARTER = 'STARTER'
    STANDARD = 'STANDARD'


class Enabled(RootModel[bool]):
    root: bool


class Framework(Enum):
    HYPERLEDGER_FABRIC = 'HYPERLEDGER_FABRIC'
    ETHEREUM = 'ETHEREUM'


class FrameworkVersionString(RootModel[constr(min_length=1, max_length=8)]):
    root: constr(min_length=1, max_length=8)


class GetAccessorInput(BaseModel):
    pass


class GetMemberInput(BaseModel):
    pass


class GetNetworkInput(BaseModel):
    pass


class GetNodeInput(BaseModel):
    pass


class GetProposalInput(BaseModel):
    pass


class IllegalActionException(RootModel[Any]):
    root: Any


class InstanceTypeString(RootModel[str]):
    root: str


class InternalServiceErrorException(RootModel[Any]):
    root: Any


class InvalidRequestException(RootModel[Any]):
    root: Any


class InvitationStatus(Enum):
    PENDING = 'PENDING'
    ACCEPTED = 'ACCEPTED'
    ACCEPTING = 'ACCEPTING'
    REJECTED = 'REJECTED'
    EXPIRED = 'EXPIRED'


class IsOwned(RootModel[bool]):
    root: bool


class ListAccessorsInput(BaseModel):
    pass


class ListInvitationsInput(BaseModel):
    pass


class ListMembersInput(BaseModel):
    pass


class ListNetworksInput(BaseModel):
    pass


class ListNodesInput(BaseModel):
    pass


class ListProposalVotesInput(BaseModel):
    pass


class ListProposalsInput(BaseModel):
    pass


class ListTagsForResourceRequest(BaseModel):
    pass


class LogConfiguration(BaseModel):
    Enabled_1: Optional[Enabled] = Field(None, alias='Enabled')


class LogConfigurations(BaseModel):
    Cloudwatch: Optional[LogConfiguration] = None


class MemberFabricLogPublishingConfiguration(BaseModel):
    CaLogs: Optional[LogConfigurations] = None


class MemberListMaxResults(RootModel[conint(ge=1, le=20)]):
    root: conint(ge=1, le=20)


class MemberLogPublishingConfiguration(BaseModel):
    Fabric: Optional[MemberFabricLogPublishingConfiguration] = None


class MemberStatus(Enum):
    CREATING = 'CREATING'
    AVAILABLE = 'AVAILABLE'
    CREATE_FAILED = 'CREATE_FAILED'
    UPDATING = 'UPDATING'
    DELETING = 'DELETING'
    DELETED = 'DELETED'
    INACCESSIBLE_ENCRYPTION_KEY = 'INACCESSIBLE_ENCRYPTION_KEY'


class NameString(RootModel[constr(pattern=r'.*\S.*', min_length=1, max_length=64)]):
    root: constr(pattern=r'.*\S.*', min_length=1, max_length=64)


class NetworkFabricConfiguration(BaseModel):
    Edition_1: Edition = Field(..., alias='Edition')


class NetworkFrameworkConfiguration(BaseModel):
    Fabric: Optional[NetworkFabricConfiguration] = None


class NetworkListMaxResults(RootModel[conint(ge=1, le=10)]):
    root: conint(ge=1, le=10)


class NetworkMemberNameString(
    RootModel[
        constr(
            pattern=r'^(?!-|[0-9])(?!.*-$)(?!.*?--)[a-zA-Z0-9-]+$',
            min_length=1,
            max_length=64,
        )
    ]
):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: constr(
        pattern=r'^(?!-|[0-9])(?!.*-$)(?!.*?--)[a-zA-Z0-9-]+$',
        min_length=1,
        max_length=64,
    )


class NetworkStatus(Enum):
    CREATING = 'CREATING'
    AVAILABLE = 'AVAILABLE'
    CREATE_FAILED = 'CREATE_FAILED'
    DELETING = 'DELETING'
    DELETED = 'DELETED'


class NodeFabricLogPublishingConfiguration(BaseModel):
    ChaincodeLogs: Optional[LogConfigurations] = None
    PeerLogs: Optional[LogConfigurations] = None


class NodeListMaxResults(RootModel[conint(ge=1, le=20)]):
    root: conint(ge=1, le=20)


class NodeLogPublishingConfiguration(BaseModel):
    Fabric: Optional[NodeFabricLogPublishingConfiguration] = None


class NodeStatus(Enum):
    CREATING = 'CREATING'
    AVAILABLE = 'AVAILABLE'
    UNHEALTHY = 'UNHEALTHY'
    CREATE_FAILED = 'CREATE_FAILED'
    UPDATING = 'UPDATING'
    DELETING = 'DELETING'
    DELETED = 'DELETED'
    FAILED = 'FAILED'
    INACCESSIBLE_ENCRYPTION_KEY = 'INACCESSIBLE_ENCRYPTION_KEY'


class PaginationToken(RootModel[constr(max_length=128)]):
    root: constr(max_length=128)


class PasswordString(RootModel[SecretStr]):
    root: SecretStr


class PrincipalString(RootModel[str]):
    root: str


class ProposalDurationInt(RootModel[conint(ge=1, le=168)]):
    root: conint(ge=1, le=168)


class ProposalListMaxResults(RootModel[conint(ge=1, le=100)]):
    root: conint(ge=1, le=100)


class ProposalStatus(Enum):
    IN_PROGRESS = 'IN_PROGRESS'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'
    EXPIRED = 'EXPIRED'
    ACTION_FAILED = 'ACTION_FAILED'


class RejectInvitationInput(BaseModel):
    pass


class RejectInvitationOutput(BaseModel):
    pass


class ResourceAlreadyExistsException(RootModel[Any]):
    root: Any


class ResourceIdString(RootModel[constr(min_length=1, max_length=32)]):
    root: constr(min_length=1, max_length=32)


class ResourceLimitExceededException(RootModel[Any]):
    root: Any


class ResourceNotFoundException(RootModel[Any]):
    root: Any


class ResourceNotReadyException(RootModel[Any]):
    root: Any


class StateDBType(Enum):
    LevelDB = 'LevelDB'
    CouchDB = 'CouchDB'


class String(RootModel[str]):
    root: str


class TagKey(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class TagKeyList(RootModel[List[TagKey]]):
    root: List[TagKey] = Field(..., max_length=200, min_length=0)


class TagResourceResponse(BaseModel):
    pass


class TagValue(RootModel[constr(min_length=0, max_length=256)]):
    root: constr(min_length=0, max_length=256)


class ThresholdComparator(Enum):
    GREATER_THAN = 'GREATER_THAN'
    GREATER_THAN_OR_EQUAL_TO = 'GREATER_THAN_OR_EQUAL_TO'


class ThresholdPercentageInt(RootModel[conint(ge=0, le=100)]):
    root: conint(ge=0, le=100)


class ThrottlingException(RootModel[Any]):
    root: Any


class Timestamp(RootModel[datetime]):
    root: datetime


class TooManyTagsException(RootModel[Any]):
    root: Any


class UntagResourceRequest(BaseModel):
    pass


class UntagResourceResponse(BaseModel):
    pass


class UpdateMemberInput(BaseModel):
    LogPublishingConfiguration: Optional[MemberLogPublishingConfiguration] = None


class UpdateMemberOutput(BaseModel):
    pass


class UpdateNodeInput(BaseModel):
    LogPublishingConfiguration: Optional[NodeLogPublishingConfiguration] = None
    MemberId: Optional[ResourceIdString] = None


class UpdateNodeOutput(BaseModel):
    pass


class UsernameString(
    RootModel[constr(pattern=r'^[a-zA-Z][a-zA-Z0-9]*$', min_length=1, max_length=16)]
):
    root: constr(pattern=r'^[a-zA-Z][a-zA-Z0-9]*$', min_length=1, max_length=16)


class VoteCount(RootModel[int]):
    root: int


class VoteOnProposalOutput(BaseModel):
    pass


class VoteValue(Enum):
    YES = 'YES'
    NO = 'NO'


class AccessorsPostRequest(BaseModel):
    AccessorType_1: AccessorType = Field(
        ...,
        alias='AccessorType',
        description='<p>The type of accessor.</p> <note> <p>Currently, accessor type is restricted to <code>BILLING_TOKEN</code>.</p> </note>',
    )
    ClientRequestToken: constr(min_length=1, max_length=64) = Field(
        ...,
        description='This is a unique, case-sensitive identifier that you provide to ensure the idempotency of the operation. An idempotent operation completes no more than once. This identifier is required only if you make a service request directly using an HTTP client. It is generated automatically if you use an Amazon Web Services SDK or the Amazon Web Services CLI.',
    )
    Tags: Optional[Dict[str, TagValue]] = Field(
        None,
        description='<p>Tags to assign to the Accessor.</p> <p> Each tag consists of a key and an optional value. You can specify multiple key-value pairs in a single request with an overall maximum of 50 tags allowed per resource.</p> <p>For more information about tags, see <a href="https://docs.aws.amazon.com/managed-blockchain/latest/ethereum-dev/tagging-resources.html">Tagging Resources</a> in the <i>Amazon Managed Blockchain Ethereum Developer Guide</i>, or <a href="https://docs.aws.amazon.com/managed-blockchain/latest/hyperledger-fabric-dev/tagging-resources.html">Tagging Resources</a> in the <i>Amazon Managed Blockchain Hyperledger Fabric Developer Guide</i>.</p>',
    )


class Status(Enum):
    CREATING = 'CREATING'
    AVAILABLE = 'AVAILABLE'
    CREATE_FAILED = 'CREATE_FAILED'
    DELETING = 'DELETING'
    DELETED = 'DELETED'


class FrameworkConfiguration(BaseModel):
    Fabric: Optional[NetworkFabricConfiguration] = None


class Status2(Enum):
    CREATING = 'CREATING'
    AVAILABLE = 'AVAILABLE'
    CREATE_FAILED = 'CREATE_FAILED'
    UPDATING = 'UPDATING'
    DELETING = 'DELETING'
    DELETED = 'DELETED'
    INACCESSIBLE_ENCRYPTION_KEY = 'INACCESSIBLE_ENCRYPTION_KEY'


class LogPublishingConfiguration(BaseModel):
    Fabric: Optional[MemberFabricLogPublishingConfiguration] = None


class NetworksNetworkIdMembersMemberIdPatchRequest(BaseModel):
    LogPublishingConfiguration_1: Optional[LogPublishingConfiguration] = Field(
        None,
        alias='LogPublishingConfiguration',
        description='Configuration properties for logging events associated with a member of a Managed Blockchain network.',
    )


class Status4(Enum):
    CREATING = 'CREATING'
    AVAILABLE = 'AVAILABLE'
    UNHEALTHY = 'UNHEALTHY'
    CREATE_FAILED = 'CREATE_FAILED'
    UPDATING = 'UPDATING'
    DELETING = 'DELETING'
    DELETED = 'DELETED'
    FAILED = 'FAILED'
    INACCESSIBLE_ENCRYPTION_KEY = 'INACCESSIBLE_ENCRYPTION_KEY'


class NodeConfiguration1(BaseModel):
    AvailabilityZone: Optional[AvailabilityZoneString] = None
    InstanceType: Optional[InstanceTypeString] = None
    LogPublishingConfiguration: Optional[NodeLogPublishingConfiguration] = None
    StateDB: Optional[StateDBType] = None


class NetworksNetworkIdNodesPostRequest(BaseModel):
    ClientRequestToken: constr(min_length=1, max_length=64) = Field(
        ...,
        description='A unique, case-sensitive identifier that you provide to ensure the idempotency of the operation. An idempotent operation completes no more than one time. This identifier is required only if you make a service request directly using an HTTP client. It is generated automatically if you use an Amazon Web Services SDK or the CLI.',
    )
    MemberId: Optional[constr(min_length=1, max_length=32)] = Field(
        None,
        description='<p>The unique identifier of the member that owns this node.</p> <p>Applies only to Hyperledger Fabric.</p>',
    )
    NodeConfiguration: NodeConfiguration1 = Field(
        ..., description='Configuration properties of a node.'
    )
    Tags: Optional[Dict[str, TagValue]] = Field(
        None,
        description='<p>Tags to assign to the node.</p> <p> Each tag consists of a key and an optional value. You can specify multiple key-value pairs in a single request with an overall maximum of 50 tags allowed per resource.</p> <p>For more information about tags, see <a href="https://docs.aws.amazon.com/managed-blockchain/latest/ethereum-dev/tagging-resources.html">Tagging Resources</a> in the <i>Amazon Managed Blockchain Ethereum Developer Guide</i>, or <a href="https://docs.aws.amazon.com/managed-blockchain/latest/hyperledger-fabric-dev/tagging-resources.html">Tagging Resources</a> in the <i>Amazon Managed Blockchain Hyperledger Fabric Developer Guide</i>.</p>',
    )


class LogPublishingConfiguration1(BaseModel):
    Fabric: Optional[NodeFabricLogPublishingConfiguration] = None


class NetworksNetworkIdNodesNodeIdPatchRequest(BaseModel):
    LogPublishingConfiguration: Optional[LogPublishingConfiguration1] = Field(
        None,
        description='Configuration properties for logging events associated with a peer node on a Hyperledger Fabric network on Managed Blockchain.',
    )
    MemberId: Optional[constr(min_length=1, max_length=32)] = Field(
        None,
        description='<p>The unique identifier of the member that owns the node.</p> <p>Applies only to Hyperledger Fabric.</p>',
    )


class Vote(Enum):
    YES = 'YES'
    NO = 'NO'


class NetworksNetworkIdProposalsProposalIdVotesPostRequest(BaseModel):
    Vote_1: Vote = Field(..., alias='Vote', description=' The value of the vote. ')
    VoterMemberId: constr(min_length=1, max_length=32) = Field(
        ..., description='The unique identifier of the member casting the vote. '
    )


class TagsResourceArnPostRequest(BaseModel):
    Tags: Dict[str, TagValue] = Field(
        ...,
        description='The tags to assign to the specified resource. Tag values can be empty, for example, <code>"MyTagKey" : ""</code>. You can specify multiple key-value pairs in a single request, with an overall maximum of 50 tags added to each resource.',
    )


class TagKeys(RootModel[List[TagKey]]):
    root: List[TagKey] = Field(..., max_length=200, min_length=0)


class AccessorSummary(BaseModel):
    Arn: Optional[ArnString] = None
    CreationDate: Optional[Timestamp] = None
    Id: Optional[ResourceIdString] = None
    Status: Optional[AccessorStatus] = None
    Type: Optional[AccessorType] = None


class AccessorSummaryList(RootModel[List[AccessorSummary]]):
    root: List[AccessorSummary]


class ApprovalThresholdPolicy(BaseModel):
    ProposalDurationInHours: Optional[ProposalDurationInt] = None
    ThresholdComparator_1: Optional[ThresholdComparator] = Field(
        None, alias='ThresholdComparator'
    )
    ThresholdPercentage: Optional[ThresholdPercentageInt] = None


class CreateAccessorOutput(BaseModel):
    AccessorId: Optional[ResourceIdString] = None
    BillingToken: Optional[AccessorBillingTokenString] = None


class CreateMemberOutput(BaseModel):
    MemberId: Optional[ResourceIdString] = None


class CreateNetworkOutput(BaseModel):
    MemberId: Optional[ResourceIdString] = None
    NetworkId: Optional[ResourceIdString] = None


class CreateNodeOutput(BaseModel):
    NodeId: Optional[ResourceIdString] = None


class CreateProposalOutput(BaseModel):
    ProposalId: Optional[ResourceIdString] = None


class InputTagMap(RootModel[Optional[Dict[str, TagValue]]]):
    root: Optional[Dict[str, TagValue]] = None


class InviteAction(BaseModel):
    Principal: PrincipalString


class InviteActionList(RootModel[List[InviteAction]]):
    root: List[InviteAction]


class ListAccessorsOutput(BaseModel):
    Accessors: Optional[AccessorSummaryList] = None
    NextToken: Optional[PaginationToken] = None


class MemberFabricAttributes(BaseModel):
    AdminUsername: Optional[UsernameString] = None
    CaEndpoint: Optional[String] = None


class MemberFabricConfiguration(BaseModel):
    AdminPassword: PasswordString
    AdminUsername: UsernameString


class MemberFrameworkAttributes(BaseModel):
    Fabric: Optional[MemberFabricAttributes] = None


class MemberFrameworkConfiguration(BaseModel):
    Fabric: Optional[MemberFabricConfiguration] = None


class MemberSummary(BaseModel):
    Arn: Optional[ArnString] = None
    CreationDate: Optional[Timestamp] = None
    Description: Optional[DescriptionString] = None
    Id: Optional[ResourceIdString] = None
    IsOwned_1: Optional[IsOwned] = Field(None, alias='IsOwned')
    Name: Optional[NetworkMemberNameString] = None
    Status: Optional[MemberStatus] = None


class MemberSummaryList(RootModel[List[MemberSummary]]):
    root: List[MemberSummary]


class NetworkEthereumAttributes(BaseModel):
    ChainId: Optional[String] = None


class NetworkFabricAttributes(BaseModel):
    Edition_1: Optional[Edition] = Field(None, alias='Edition')
    OrderingServiceEndpoint: Optional[String] = None


class NetworkFrameworkAttributes(BaseModel):
    Ethereum: Optional[NetworkEthereumAttributes] = None
    Fabric: Optional[NetworkFabricAttributes] = None


class NetworkSummary(BaseModel):
    Arn: Optional[ArnString] = None
    CreationDate: Optional[Timestamp] = None
    Description: Optional[DescriptionString] = None
    Framework_1: Optional[Framework] = Field(None, alias='Framework')
    FrameworkVersion: Optional[FrameworkVersionString] = None
    Id: Optional[ResourceIdString] = None
    Name: Optional[NameString] = None
    Status: Optional[NetworkStatus] = None


class NetworkSummaryList(RootModel[List[NetworkSummary]]):
    root: List[NetworkSummary]


class NodeConfiguration(BaseModel):
    AvailabilityZone: Optional[AvailabilityZoneString] = None
    InstanceType: InstanceTypeString
    LogPublishingConfiguration: Optional[NodeLogPublishingConfiguration] = None
    StateDB: Optional[StateDBType] = None


class NodeEthereumAttributes(BaseModel):
    HttpEndpoint: Optional[String] = None
    WebSocketEndpoint: Optional[String] = None


class NodeFabricAttributes(BaseModel):
    PeerEndpoint: Optional[String] = None
    PeerEventEndpoint: Optional[String] = None


class NodeFrameworkAttributes(BaseModel):
    Ethereum: Optional[NodeEthereumAttributes] = None
    Fabric: Optional[NodeFabricAttributes] = None


class NodeSummary(BaseModel):
    Arn: Optional[ArnString] = None
    AvailabilityZone: Optional[AvailabilityZoneString] = None
    CreationDate: Optional[Timestamp] = None
    Id: Optional[ResourceIdString] = None
    InstanceType: Optional[InstanceTypeString] = None
    Status: Optional[NodeStatus] = None


class NodeSummaryList(RootModel[List[NodeSummary]]):
    root: List[NodeSummary]


class OutputTagMap(RootModel[Optional[Dict[str, TagValue]]]):
    root: Optional[Dict[str, TagValue]] = None


class ProposalSummary(BaseModel):
    Arn: Optional[ArnString] = None
    CreationDate: Optional[Timestamp] = None
    Description: Optional[DescriptionString] = None
    ExpirationDate: Optional[Timestamp] = None
    ProposalId: Optional[ResourceIdString] = None
    ProposedByMemberId: Optional[ResourceIdString] = None
    ProposedByMemberName: Optional[NetworkMemberNameString] = None
    Status: Optional[ProposalStatus] = None


class ProposalSummaryList(RootModel[List[ProposalSummary]]):
    root: List[ProposalSummary]


class RemoveAction(BaseModel):
    MemberId: ResourceIdString


class RemoveActionList(RootModel[List[RemoveAction]]):
    root: List[RemoveAction]


class TagResourceRequest(BaseModel):
    Tags: InputTagMap


class VoteOnProposalInput(BaseModel):
    Vote: VoteValue
    VoterMemberId: ResourceIdString


class VoteSummary(BaseModel):
    MemberId: Optional[ResourceIdString] = None
    MemberName: Optional[NetworkMemberNameString] = None
    Vote: Optional[VoteValue] = None


class VotingPolicy(BaseModel):
    ApprovalThresholdPolicy_1: Optional[ApprovalThresholdPolicy] = Field(
        None, alias='ApprovalThresholdPolicy'
    )


class MemberConfiguration1(BaseModel):
    Description: Optional[DescriptionString] = None
    FrameworkConfiguration: Optional[MemberFrameworkConfiguration] = None
    KmsKeyArn: Optional[ArnString] = None
    LogPublishingConfiguration: Optional[MemberLogPublishingConfiguration] = None
    Name: Optional[NetworkMemberNameString] = None
    Tags: Optional[InputTagMap] = None


class NetworksPostRequest(BaseModel):
    ClientRequestToken: constr(min_length=1, max_length=64) = Field(
        ...,
        description='This is a unique, case-sensitive identifier that you provide to ensure the idempotency of the operation. An idempotent operation completes no more than once. This identifier is required only if you make a service request directly using an HTTP client. It is generated automatically if you use an Amazon Web Services SDK or the Amazon Web Services CLI. ',
    )
    Description: Optional[constr(max_length=128)] = Field(
        None, description='An optional description for the network.'
    )
    Framework_1: Framework = Field(
        ...,
        alias='Framework',
        description='The blockchain framework that the network uses.',
    )
    FrameworkConfiguration_1: Optional[FrameworkConfiguration] = Field(
        None,
        alias='FrameworkConfiguration',
        description=' Configuration properties relevant to the network for the blockchain framework that the network uses. ',
    )
    FrameworkVersion: constr(min_length=1, max_length=8) = Field(
        ...,
        description='The version of the blockchain framework that the network uses.',
    )
    MemberConfiguration: MemberConfiguration1 = Field(
        ...,
        description='<p>Configuration properties of the member.</p> <p>Applies only to Hyperledger Fabric.</p>',
    )
    Name: constr(pattern=r'.*\S.*', min_length=1, max_length=64) = Field(
        ..., description='The name of the network.'
    )
    Tags: Optional[Dict[str, TagValue]] = Field(
        None,
        description='<p>Tags to assign to the network.</p> <p> Each tag consists of a key and an optional value. You can specify multiple key-value pairs in a single request with an overall maximum of 50 tags allowed per resource.</p> <p>For more information about tags, see <a href="https://docs.aws.amazon.com/managed-blockchain/latest/ethereum-dev/tagging-resources.html">Tagging Resources</a> in the <i>Amazon Managed Blockchain Ethereum Developer Guide</i>, or <a href="https://docs.aws.amazon.com/managed-blockchain/latest/hyperledger-fabric-dev/tagging-resources.html">Tagging Resources</a> in the <i>Amazon Managed Blockchain Hyperledger Fabric Developer Guide</i>.</p>',
    )
    VotingPolicy_1: VotingPolicy = Field(
        ...,
        alias='VotingPolicy',
        description='<p> The voting rules for the network to decide if a proposal is accepted </p> <p>Applies only to Hyperledger Fabric.</p>',
    )


class NetworksNetworkIdMembersPostRequest(BaseModel):
    ClientRequestToken: constr(min_length=1, max_length=64) = Field(
        ...,
        description='A unique, case-sensitive identifier that you provide to ensure the idempotency of the operation. An idempotent operation completes no more than one time. This identifier is required only if you make a service request directly using an HTTP client. It is generated automatically if you use an Amazon Web Services SDK or the CLI.',
    )
    InvitationId: constr(min_length=1, max_length=32) = Field(
        ...,
        description='The unique identifier of the invitation that is sent to the member to join the network.',
    )
    MemberConfiguration: MemberConfiguration1 = Field(
        ...,
        description='<p>Configuration properties of the member.</p> <p>Applies only to Hyperledger Fabric.</p>',
    )


class Actions(BaseModel):
    Invitations: Optional[InviteActionList] = None
    Removals: Optional[RemoveActionList] = None


class NetworksNetworkIdProposalsPostRequest(BaseModel):
    Actions_1: Actions = Field(
        ...,
        alias='Actions',
        description='<p> The actions to carry out if a proposal is <code>APPROVED</code>. </p> <p>Applies only to Hyperledger Fabric.</p>',
    )
    ClientRequestToken: constr(min_length=1, max_length=64) = Field(
        ...,
        description='A unique, case-sensitive identifier that you provide to ensure the idempotency of the operation. An idempotent operation completes no more than one time. This identifier is required only if you make a service request directly using an HTTP client. It is generated automatically if you use an Amazon Web Services SDK or the CLI.',
    )
    Description: Optional[constr(max_length=128)] = Field(
        None,
        description='A description for the proposal that is visible to voting members, for example, "Proposal to add Example Corp. as member."',
    )
    MemberId: constr(min_length=1, max_length=32) = Field(
        ...,
        description='The unique identifier of the member that is creating the proposal. This identifier is especially useful for identifying the member making the proposal when multiple members exist in a single Amazon Web Services account.',
    )
    Tags: Optional[Dict[str, TagValue]] = Field(
        None,
        description='<p>Tags to assign to the proposal.</p> <p> Each tag consists of a key and an optional value. You can specify multiple key-value pairs in a single request with an overall maximum of 50 tags allowed per resource.</p> <p>For more information about tags, see <a href="https://docs.aws.amazon.com/managed-blockchain/latest/ethereum-dev/tagging-resources.html">Tagging Resources</a> in the <i>Amazon Managed Blockchain Ethereum Developer Guide</i>, or <a href="https://docs.aws.amazon.com/managed-blockchain/latest/hyperledger-fabric-dev/tagging-resources.html">Tagging Resources</a> in the <i>Amazon Managed Blockchain Hyperledger Fabric Developer Guide</i>.</p>',
    )


class Accessor(BaseModel):
    Arn: Optional[ArnString] = None
    BillingToken: Optional[AccessorBillingTokenString] = None
    CreationDate: Optional[Timestamp] = None
    Id: Optional[ResourceIdString] = None
    Status: Optional[AccessorStatus] = None
    Tags: Optional[OutputTagMap] = None
    Type: Optional[AccessorType] = None


class CreateAccessorInput(BaseModel):
    AccessorType_1: AccessorType = Field(..., alias='AccessorType')
    ClientRequestToken: ClientRequestTokenString
    Tags: Optional[InputTagMap] = None


class CreateNodeInput(BaseModel):
    ClientRequestToken: ClientRequestTokenString
    MemberId: Optional[ResourceIdString] = None
    NodeConfiguration_1: NodeConfiguration = Field(..., alias='NodeConfiguration')
    Tags: Optional[InputTagMap] = None


class GetAccessorOutput(BaseModel):
    Accessor_1: Optional[Accessor] = Field(None, alias='Accessor')


class Invitation(BaseModel):
    Arn: Optional[ArnString] = None
    CreationDate: Optional[Timestamp] = None
    ExpirationDate: Optional[Timestamp] = None
    InvitationId: Optional[ResourceIdString] = None
    NetworkSummary_1: Optional[NetworkSummary] = Field(None, alias='NetworkSummary')
    Status: Optional[InvitationStatus] = None


class InvitationList(RootModel[List[Invitation]]):
    root: List[Invitation]


class ListInvitationsOutput(BaseModel):
    Invitations: Optional[InvitationList] = None
    NextToken: Optional[PaginationToken] = None


class ListMembersOutput(BaseModel):
    Members: Optional[MemberSummaryList] = None
    NextToken: Optional[PaginationToken] = None


class ListNetworksOutput(BaseModel):
    Networks: Optional[NetworkSummaryList] = None
    NextToken: Optional[PaginationToken] = None


class ListNodesOutput(BaseModel):
    NextToken: Optional[PaginationToken] = None
    Nodes: Optional[NodeSummaryList] = None


class ListProposalsOutput(BaseModel):
    NextToken: Optional[PaginationToken] = None
    Proposals: Optional[ProposalSummaryList] = None


class ListTagsForResourceResponse(BaseModel):
    Tags: Optional[OutputTagMap] = None


class Member(BaseModel):
    Arn: Optional[ArnString] = None
    CreationDate: Optional[Timestamp] = None
    Description: Optional[DescriptionString] = None
    FrameworkAttributes: Optional[MemberFrameworkAttributes] = None
    Id: Optional[ResourceIdString] = None
    KmsKeyArn: Optional[String] = None
    LogPublishingConfiguration: Optional[MemberLogPublishingConfiguration] = None
    Name: Optional[NetworkMemberNameString] = None
    NetworkId: Optional[ResourceIdString] = None
    Status: Optional[MemberStatus] = None
    Tags: Optional[OutputTagMap] = None


class MemberConfiguration(BaseModel):
    Description: Optional[DescriptionString] = None
    FrameworkConfiguration: MemberFrameworkConfiguration
    KmsKeyArn: Optional[ArnString] = None
    LogPublishingConfiguration: Optional[MemberLogPublishingConfiguration] = None
    Name: NetworkMemberNameString
    Tags: Optional[InputTagMap] = None


class Network(BaseModel):
    Arn: Optional[ArnString] = None
    CreationDate: Optional[Timestamp] = None
    Description: Optional[DescriptionString] = None
    Framework_1: Optional[Framework] = Field(None, alias='Framework')
    FrameworkAttributes: Optional[NetworkFrameworkAttributes] = None
    FrameworkVersion: Optional[FrameworkVersionString] = None
    Id: Optional[ResourceIdString] = None
    Name: Optional[NameString] = None
    Status: Optional[NetworkStatus] = None
    Tags: Optional[OutputTagMap] = None
    VotingPolicy_1: Optional[VotingPolicy] = Field(None, alias='VotingPolicy')
    VpcEndpointServiceName: Optional[String] = None


class Node(BaseModel):
    Arn: Optional[ArnString] = None
    AvailabilityZone: Optional[AvailabilityZoneString] = None
    CreationDate: Optional[Timestamp] = None
    FrameworkAttributes: Optional[NodeFrameworkAttributes] = None
    Id: Optional[ResourceIdString] = None
    InstanceType: Optional[InstanceTypeString] = None
    KmsKeyArn: Optional[String] = None
    LogPublishingConfiguration: Optional[NodeLogPublishingConfiguration] = None
    MemberId: Optional[ResourceIdString] = None
    NetworkId: Optional[ResourceIdString] = None
    StateDB: Optional[StateDBType] = None
    Status: Optional[NodeStatus] = None
    Tags: Optional[OutputTagMap] = None


class ProposalActions(BaseModel):
    Invitations: Optional[InviteActionList] = None
    Removals: Optional[RemoveActionList] = None


class ProposalVoteList(RootModel[List[VoteSummary]]):
    root: List[VoteSummary]


class CreateMemberInput(BaseModel):
    ClientRequestToken: ClientRequestTokenString
    InvitationId: ResourceIdString
    MemberConfiguration_1: MemberConfiguration = Field(..., alias='MemberConfiguration')


class CreateNetworkInput(BaseModel):
    ClientRequestToken: ClientRequestTokenString
    Description: Optional[DescriptionString] = None
    Framework_1: Framework = Field(..., alias='Framework')
    FrameworkConfiguration: Optional[NetworkFrameworkConfiguration] = None
    FrameworkVersion: FrameworkVersionString
    MemberConfiguration_1: MemberConfiguration = Field(..., alias='MemberConfiguration')
    Name: NameString
    Tags: Optional[InputTagMap] = None
    VotingPolicy_1: VotingPolicy = Field(..., alias='VotingPolicy')


class CreateProposalInput(BaseModel):
    Actions: ProposalActions
    ClientRequestToken: ClientRequestTokenString
    Description: Optional[DescriptionString] = None
    MemberId: ResourceIdString
    Tags: Optional[InputTagMap] = None


class GetMemberOutput(BaseModel):
    Member_1: Optional[Member] = Field(None, alias='Member')


class GetNetworkOutput(BaseModel):
    Network_1: Optional[Network] = Field(None, alias='Network')


class GetNodeOutput(BaseModel):
    Node_1: Optional[Node] = Field(None, alias='Node')


class ListProposalVotesOutput(BaseModel):
    NextToken: Optional[PaginationToken] = None
    ProposalVotes: Optional[ProposalVoteList] = None


class Proposal(BaseModel):
    Actions: Optional[ProposalActions] = None
    Arn: Optional[ArnString] = None
    CreationDate: Optional[Timestamp] = None
    Description: Optional[DescriptionString] = None
    ExpirationDate: Optional[Timestamp] = None
    NetworkId: Optional[ResourceIdString] = None
    NoVoteCount: Optional[VoteCount] = None
    OutstandingVoteCount: Optional[VoteCount] = None
    ProposalId: Optional[ResourceIdString] = None
    ProposedByMemberId: Optional[ResourceIdString] = None
    ProposedByMemberName: Optional[NetworkMemberNameString] = None
    Status: Optional[ProposalStatus] = None
    Tags: Optional[OutputTagMap] = None
    YesVoteCount: Optional[VoteCount] = None


class GetProposalOutput(BaseModel):
    Proposal_1: Optional[Proposal] = Field(None, alias='Proposal')
